<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Activity_model extends CI_Model
{

    public $table = 'activity_log';
    public $id = 'id_activity';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    function show_all(){

        // $hasil=$this->db->query("SELECT * FROM mahasiswa");
        // $hasil = $this->db->get('mahasiswa');  
        // return $hasil;
        // return $this->db->get('activity_log');
        $this->db->from('activity_log');
$this->db->order_by("waktu", "desc");
        return $this->db->get();



  }    
    // datatables
    function json() {
        $this->datatables->select('*');
        $this->datatables->from('activity');
     
        //add this line for join
        //$this->datatables->join('table2', 'produk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('activity/read/$1'),'Read')." | ".anchor(site_url('activity/update/$1'),'Update')." | ".anchor(site_url('activity/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_activity');
        return $this->datatables->generate();
    }
//  get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_activity', $q);
	$this->db->or_like('kegiatan', $q);
	$this->db->or_like('waktu', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_activity', $q);
	$this->db->or_like('kegiatan', $q);
	$this->db->or_like('waktu', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($hal)
    {
        $this->db->insert($this->table, $hal);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Produk_model.php */
/* Location: ./application/models/Produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-05 11:20:19 */
/* http://harviacode.com */