<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_foto_model extends CI_Model
{

    public $table = 'produk_foto';
    public $id = 'id_produk_foto';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_produk_foto,foto_produk,id_produk');
        $this->datatables->from('produk_foto');
        // $this->datatables->join('produk','produk.id_user = produk_foto.id_user');
        //add this line for join
        //$this->datatables->join('table2', 'produk_foto.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('produk_foto/read/$1'),'Read')." | ".anchor(site_url('produk_foto/update/$1'),'Update')." | ".anchor(site_url('produk_foto/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_produk_foto');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_produk_foto', $q);
	$this->db->or_like('foto_produk', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk_foto', $q);
	$this->db->or_like('foto_produk', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Produk_foto_model.php */
/* Location: ./application/models/Produk_foto_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-05 11:20:34 */
/* http://harviacode.com */