  <?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_model extends CI_Model
{

    public $table = 'produk';
    public $id = 'id_produk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_produk,kode_produk,nama_produk,deskripsi_produk,harga_beli_produk,harga_jual_produk,status,harga_jual_produk_sup,satuan');
        $this->datatables->from('produk');
     
        //add this line for join
        //$this->datatables->join('table2', 'produk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('produk/read/$1'),'Read')." | ".anchor(site_url('produk/update/$1'),'Update')." | ".anchor(site_url('produk/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_produk');
        return $this->datatables->generate();
    }
    function get_nama($nama){
        $this->db->select('*');
        $this->db->from('produk');
        $this->db->like('nama_produk', $nama);
        return $this->db->get()->result_array();

    }

    function search_produk($kode_produk){
        $this->db->like('kode_produk', $kode_produk , 'both');
        $this->db->order_by('kode_produk', 'ASC');
        $this->db->limit(15);
        return $this->db->get('produk')->result();
    }
    function get_kode($kode_p){
        $q = $this->db->query("SELECT MAX(RIGHT(kode_produk,4)) AS kd_max FROM produk WHERE kode_produk like '".$kode_p."%'");
        $result = $q->result();
        $kd = "";
        if($q->num_rows()>0){
            foreach($q->result() as $k){
                $tmp = ((int)$k->kd_max)+1;
                $kd = $kode_p.sprintf("%04s", $tmp);
              
            }
        }else{
            $kd = $kode_p."0001";
        }
        return $kd;

    }
    function product_list(){
        $hasil=$this->db->get('produk');
        return $hasil->result();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_barang($kode_produk){
        $hsl=$this->db->query("SELECT * FROM produk where kode_produk='$kode_produk'");
		return $hsl;
    }
    function tampil_barang(){
        $hsl= $this->db->query("SELECT * FROM produk");
        return $hsl;
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_produk', $q);
	$this->db->or_like('kode_produk', $q);
	$this->db->or_like('nama_produk', $q);
	$this->db->or_like('deskripsi_produk', $q);
	$this->db->or_like('harga_beli_produk', $q);
	$this->db->or_like('harga_jual_produk', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk', $q);
	$this->db->or_like('kode_produk', $q);
	$this->db->or_like('nama_produk', $q);
	$this->db->or_like('deskripsi_produk', $q);
	$this->db->or_like('harga_beli_produk', $q);
	$this->db->or_like('harga_jual_produk', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Produk_model.php */
/* Location: ./application/models/Produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-05 11:20:19 */
/* http://harviacode.com */