<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Produk_stok_model extends CI_Model
{

    public $table = 'produk_stok';
    public $id = 'id_produk_stok';
    public $order = 'DESC';

    public function __construct()
    {
        parent::__construct();
    }

    // datatables
    public function json()
    {
        $this->datatables->select('id_produk_stok,kode_produk,nama_produk,tanggal_produk_stok,jumlah_produk_stok');
        $this->datatables->from('v_produk_stok');
        //add this line for join
        // $this->datatables->join('produk', 'produk_stok.id_produk_stok = produk.id_produk');
        $this->datatables->add_column('action', anchor(site_url('produk_stok/read/$1'), 'Read') . " | " . anchor(site_url('produk_stok/update/$1'), 'Update') . " | " . anchor(site_url('produk_stok/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_produk_stok');
        return $this->datatables->generate();
    }

    // get all
    public function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    public function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    public function total_rows($q = null)
    {
        $this->db->like('id_produk_stok', $q);
        $this->db->or_like('id_produk', $q);
        $this->db->or_like('tanggal_produk_stok', $q);
        $this->db->or_like('jumlah_produk_stok', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    public function get_limit_data($limit, $start = 0, $q = null)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk_stok', $q);
        $this->db->or_like('id_produk', $q);
        $this->db->or_like('tanggal_produk_stok', $q);
        $this->db->or_like('jumlah_produk_stok', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    public function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    public function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    public function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Produk_stok_model.php */
/* Location: ./application/models/Produk_stok_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-05 11:20:23 */
/* http://harviacode.com */