<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_penjualan_model extends CI_Model
{

    public $table = 'produk_penjualan';
    public $id = 'id_produk_penjualan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_produk_penjualan,id_penjualan,id_produk,qty');
        $this->datatables->from('produk_penjualan');
        //add this line for join
        //$this->datatables->join('table2', 'produk_penjualan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('produk_penjualan/read/$1'),'Read')." | ".anchor(site_url('produk_penjualan/update/$1'),'Update')." | ".anchor(site_url('produk_penjualan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_produk_penjualan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_produk_penjualan', $q);
	$this->db->or_like('id_penjualan', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('qty', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk_penjualan', $q);
	$this->db->or_like('id_penjualan', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('qty', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Produk_penjualan_model.php */
/* Location: ./application/models/Produk_penjualan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-05 11:20:30 */
/* http://harviacode.com */